# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11MgDSmeCkXcdaKd44lWhaSyiJFCCKh_p
"""

!pip install streamlit
import streamlit as st
import pandas as pd

st.file_uploader("Pick a file")

